### ISSUE TITLE
New approved initiative is not shown in the browse view

### ISSUE THREAD

**Issue by iperdomo** [akvo/unep-gpml#220] opened 2021-05-05 19:01 UTC
Newly approved initiative
![2021-05-05_1137x237.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/27748e3d-da18-4130-a8f1-9d3896e4d929)

It doesn't show by searching
![2021-05-05_1620x326.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/fdf988b7-5e87-40c6-8dd0-ba340965453b)

Nor in the most recent list
![2021-05-05_1643x639.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/aa930570-0acc-4db5-98a3-b5ae47164786)

**Comment by punchagan** [comment] 2021-06-24 09:14
Unable to reproduce this with any of the different geo coverage values, on the current main branch. 
cdb126f59728b1f586c5b6b37937149800228d4d probably has fixed the bug reported here. I'm in favor of closing this, and re-opening or creating a new ticket, if we notice something again.

**Closed** 2021-06-25 17:35 UTC
Labels: bug
