### ISSUE TITLE
Individuals/Entities Details View is not showing

### ISSUE THREAD

**Issue by irenewestra** [akvo/unep-gpml#355] opened 2021-07-27 06:04 UTC
When you are logged in and want to see the details of e.g. https://digital.gpmarinelitter.org/organisation/344, you get the following page:

![Screenshot 2021-07-27 at 09.01.40.png](https://images.zenhubusercontent.com/604b12ea02390db1b594f304/1671b88f-389a-421e-991e-6ad2ca6c49c8)

**Comment by punchagan** [comment] 2021-07-27 06:21
Duplicate of #346

**Closed by punchagan** 2021-07-27 06:21 UTC
Labels: bug
